spring.application.name=deliveryboy
# Kafka Bootstrap Server
spring.kafka.bootstrap-servers=localhost:9092

# Producer Configurations
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer